version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-ultimate
      POSTGRES_DB: ultimate-chats

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      SPRING_CASSANDRA_CONTACT_POINTS: cassandra
      CASSANDRA_KEYSPACE: ultimate_chats
      CASSANDRA_USER: cassandra-user
      CASSANDRA_PASSWORD: cassandra-ultimate

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq-user
      RABBITMQ_DEFAULT_PASS: rabbitmq-ultimate

