spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    platform: postgres
    jdbcUrl: jdbc:postgresql://localhost:5432/ultimate-chats
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ultimate-chats
    username: postgres
    password: postgres-ultimate

  data:
    cassandra:
      contact-points: cassandra
      keyspace-name: ultimate_chats
      username: cassandra-user
      password: cassandra-ultimate

  mail:
    host: smtp.gmail.com
    port: 587
    username: mailerbot100@gmail.com
    password: vadqpooqdqygmbvc
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq-user
    password: rabbitmq-ultimate

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

ultimatechatapp:
  jwt:
    secret: da3HNUYhfakegjny738muHr89epqforgnOUIASJkmhjKHJ8wte
  app:
    url: http://localhost:8080